---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: default
    spec:
      containers:
      - image: nginx:mainline
        name: nginx
        securityContext:
          capabilities:
            add:
            - CAP_SYS_ADMIN

