---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: default
    spec:
      containers:
      - image: nginx:mainline
        name: nginx
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: nginx
#  name: nginx
#  namespace: default
#spec:
#  type: NodePort
#  ports:
#  - port: 80
#    protocol: TCP
#    targetPort: 80
#    nodePort: 30001
#  selector:
#    app: nginx

